name: Deploy Lambda

on:
  push:
    branches:
      - main
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip jq zip
        pip3 install boto3

    - name: Install Python dependencies and Package Lambda
      run: |
        cd lambda_function
        pip3 install -r requirements.txt -t ./
        rm -rf numpy/.*
        rm -rf pandas/.*
        zip -r ../lambda.zip .
        cd ..

    - name: Set environment variables
      id: set-env-vars
      run: |
        if [[ "${{ github.ref_name }}" == "main" ]]; then
          echo "ENV=test" >> $GITHUB_ENV
          echo "API_KEY=prod_api_key" >> $GITHUB_ENV
          echo "LOG_LEVEL=INFO" >> $GITHUB_ENV
        else
          echo "ENV=test" >> $GITHUB_ENV
          echo "API_KEY=test_api_key" >> $GITHUB_ENV
          echo "LOG_LEVEL=DEBUG" >> $GITHUB_ENV

    - name: Deploy to AWS Lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
        ENV: ${{ env.ENV }}
        API_KEY: ${{ env.API_KEY }}
        LOG_LEVEL: ${{ env.LOG_LEVEL }}
      run: |
        FUNCTION_NAME="cicd_lambda_${{ github.ref_name }}"
        REGION="us-east-1"
        echo "Deploying to Lambda function: $FUNCTION_NAME"

        # Check if the Lambda function exists
        FUNCTION_EXISTS=$(aws lambda get-function --function-name $FUNCTION_NAME --region $REGION || echo "false")

        if [ "$FUNCTION_EXISTS" == "false" ]; then
          echo "Creating Lambda function $FUNCTION_NAME..."
          aws lambda create-function \
            --function-name $FUNCTION_NAME \
            --runtime python3.9 \
            --role arn:aws:iam::851725469799:role/service-role/test_function-role-k06sk5ka \
            --handler app.lambda_handler \
            --timeout 300 \
            --zip-file fileb://lambda.zip \
            --region $REGION \
            --environment Variables="{ENV=${ENV},API_KEY=${API_KEY},LOG_LEVEL=${LOG_LEVEL}}"
        else
          echo "Updating Lambda function $FUNCTION_NAME..."
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --region $REGION \
            --zip-file fileb://lambda.zip

          aws lambda update-function-configuration \
            --function-name $FUNCTION_NAME \
            --region $REGION \
            --environment Variables="{ENV=${ENV},API_KEY=${API_KEY},LOG_LEVEL=${LOG_LEVEL}}"
        fi