name: Lambda CICD Deployment

on:
  push:
    branches:
      - test
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set Up Python Environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    # Step 3: Install Dependencies
    - name: Install dependencies
      run: |
        cd lambda_function
        pip install -r requirements.txt -t .

    # Step 4: Install jq
    - name: Install jq
      run: sudo apt-get install -y jq

    # Step 5: Package Lambda Function
    - name: Package Lambda Function
      run: |
        cd lambda_function
        zip -r ../lambda.zip .

    # Step 6: Deploy to AWS Lambda
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to AWS Lambda
      run: |
        FUNCTION_NAME="cicd_lambda_${{ github.ref_name }}"
        ENV_FILE="environment_variables/${{ github.ref_name }}.json"

        # Check if Lambda function exists
        FUNCTION_EXISTS=$(aws lambda get-function --function-name $FUNCTION_NAME || echo "false")

        if [ "$FUNCTION_EXISTS" == "false" ]; then
          echo "Creating Lambda function $FUNCTION_NAME..."
          aws lambda create-function \
            --function-name $FUNCTION_NAME \
            --runtime python3.9 \
            --role arn:aws:iam::851725469799:role/service-role/test_function-role-k06sk5ka \
            --handler app.lambda_handler \
            --timeout 300 \
            --zip-file fileb://lambda.zip \
            --environment Variables="$(cat $ENV_FILE | jq -c .)"
        else
          echo "Updating Lambda function $FUNCTION_NAME..."
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --zip-file fileb://lambda.zip

          aws lambda update-function-configuration \
            --function-name $FUNCTION_NAME \
            --environment Variables="$(cat $ENV_FILE | jq -c .)"
        fi